spring.application.name=task-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=nejragutic

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true